model:
  !include ../../base_model/llama/standard.yaml

patch:
  !include ../../patch/yarn/yarn.yaml

task:
  data: gaussian
  name: noisy_linear_regression
  curriculum: 
    !include ../../hyperparams/curriculum/dim-50_pts-200.yaml

training:
  !include ../../hyperparams/training_args.yaml

wandb:
  !include ../../logging/wandb.yaml